/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AppWgPeersIndexRouteImport } from './routes/_app/wg/peers.index'

const AppActivityLazyRouteImport = createFileRoute('/_app/activity')()
const AppJobsLazyRouteImport = createFileRoute('/_app/jobs')()
const AppProfileLazyRouteImport = createFileRoute('/_app/profile')()
const AppSecurityLazyRouteImport = createFileRoute('/_app/security')()
const AuthForgotPasswordLazyRouteImport = createFileRoute(
  '/_auth/forgot-password',
)()
const AuthSignInLazyRouteImport = createFileRoute('/_auth/sign-in')()
const AuthSignUpLazyRouteImport = createFileRoute('/_auth/sign-up')()
const AppAdminApiKeysLazyRouteImport = createFileRoute('/_app/admin/api-keys')()
const AppAdminAuditLazyRouteImport = createFileRoute('/_app/admin/audit')()
const AppAdminRolesLazyRouteImport = createFileRoute('/_app/admin/roles')()
const AppAdminUsersLazyRouteImport = createFileRoute('/_app/admin/users')()
const AppWgEndpointsLazyRouteImport = createFileRoute('/_app/wg/endpoints')()
const AppWgForwardsLazyRouteImport = createFileRoute('/_app/wg/forwards')()
const AppWgSocksLazyRouteImport = createFileRoute('/_app/wg/socks')()
const AppWgStatsLazyRouteImport = createFileRoute('/_app/wg/stats')()
const AppWgInterfacesInterfaceIdLazyRouteImport = createFileRoute(
  '/_app/wg/interfaces/$interfaceId',
)()
const AppWgNodesIndexLazyRouteImport = createFileRoute('/_app/wg/nodes/')()
const AppWgNodesNodeIdLazyRouteImport = createFileRoute(
  '/_app/wg/nodes/$nodeId',
)()
const AppWgPeersPeerIdLazyRouteImport = createFileRoute(
  '/_app/wg/peers/$peerId',
)()

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityLazyRoute = AppActivityLazyRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/activity.lazy').then((d) => d.Route))
const AppJobsLazyRoute = AppJobsLazyRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/jobs.lazy').then((d) => d.Route))
const AppProfileLazyRoute = AppProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/profile.lazy').then((d) => d.Route))
const AppSecurityLazyRoute = AppSecurityLazyRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/security.lazy').then((d) => d.Route))
const AuthForgotPasswordLazyRoute = AuthForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/forgot-password.lazy').then((d) => d.Route),
)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/reset-password.lazy').then((d) => d.Route),
)
const AuthSignInLazyRoute = AuthSignInLazyRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-in.lazy').then((d) => d.Route))
const AuthSignUpLazyRoute = AuthSignUpLazyRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-up.lazy').then((d) => d.Route))
const AppAdminApiKeysLazyRoute = AppAdminApiKeysLazyRouteImport.update({
  id: '/admin/api-keys',
  path: '/admin/api-keys',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/api-keys.lazy').then((d) => d.Route),
)
const AppAdminAuditLazyRoute = AppAdminAuditLazyRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/audit.lazy').then((d) => d.Route),
)
const AppAdminRolesLazyRoute = AppAdminRolesLazyRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/roles.lazy').then((d) => d.Route),
)
const AppAdminUsersLazyRoute = AppAdminUsersLazyRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users.lazy').then((d) => d.Route),
)
const AppWgEndpointsLazyRoute = AppWgEndpointsLazyRouteImport.update({
  id: '/wg/endpoints',
  path: '/wg/endpoints',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/wg/endpoints.lazy').then((d) => d.Route),
)
const AppWgForwardsLazyRoute = AppWgForwardsLazyRouteImport.update({
  id: '/wg/forwards',
  path: '/wg/forwards',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/wg/forwards.lazy').then((d) => d.Route),
)
const AppWgSocksLazyRoute = AppWgSocksLazyRouteImport.update({
  id: '/wg/socks',
  path: '/wg/socks',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/wg/socks.lazy').then((d) => d.Route))
const AppWgStatsLazyRoute = AppWgStatsLazyRouteImport.update({
  id: '/wg/stats',
  path: '/wg/stats',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/wg/stats.lazy').then((d) => d.Route))
const AppWgInterfacesInterfaceIdLazyRoute =
  AppWgInterfacesInterfaceIdLazyRouteImport.update({
    id: '/wg/interfaces/$interfaceId',
    path: '/wg/interfaces/$interfaceId',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/wg/interfaces.$interfaceId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppWgNodesIndexLazyRoute = AppWgNodesIndexLazyRouteImport.update({
  id: '/wg/nodes/',
  path: '/wg/nodes/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/wg/nodes.index.lazy').then((d) => d.Route),
)
const AppWgNodesNodeIdLazyRoute = AppWgNodesNodeIdLazyRouteImport.update({
  id: '/wg/nodes/$nodeId',
  path: '/wg/nodes/$nodeId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/wg/nodes.$nodeId.lazy').then((d) => d.Route),
)
const AppWgPeersIndexRoute = AppWgPeersIndexRouteImport.update({
  id: '/wg/peers/',
  path: '/wg/peers/',
  getParentRoute: () => AppRoute,
} as any)
const AppWgPeersPeerIdLazyRoute = AppWgPeersPeerIdLazyRouteImport.update({
  id: '/wg/peers/$peerId',
  path: '/wg/peers/$peerId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/wg/peers.$peerId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/activity': typeof AppActivityLazyRoute
  '/jobs': typeof AppJobsLazyRoute
  '/profile': typeof AppProfileLazyRoute
  '/security': typeof AppSecurityLazyRoute
  '/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/sign-in': typeof AuthSignInLazyRoute
  '/sign-up': typeof AuthSignUpLazyRoute
  '/admin/api-keys': typeof AppAdminApiKeysLazyRoute
  '/admin/audit': typeof AppAdminAuditLazyRoute
  '/admin/roles': typeof AppAdminRolesLazyRoute
  '/admin/users': typeof AppAdminUsersLazyRoute
  '/wg/endpoints': typeof AppWgEndpointsLazyRoute
  '/wg/forwards': typeof AppWgForwardsLazyRoute
  '/wg/socks': typeof AppWgSocksLazyRoute
  '/wg/stats': typeof AppWgStatsLazyRoute
  '/wg/interfaces/$interfaceId': typeof AppWgInterfacesInterfaceIdLazyRoute
  '/wg/nodes/$nodeId': typeof AppWgNodesNodeIdLazyRoute
  '/wg/peers/$peerId': typeof AppWgPeersPeerIdLazyRoute
  '/wg/peers/': typeof AppWgPeersIndexRoute
  '/wg/nodes/': typeof AppWgNodesIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/activity': typeof AppActivityLazyRoute
  '/jobs': typeof AppJobsLazyRoute
  '/profile': typeof AppProfileLazyRoute
  '/security': typeof AppSecurityLazyRoute
  '/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/sign-in': typeof AuthSignInLazyRoute
  '/sign-up': typeof AuthSignUpLazyRoute
  '/admin/api-keys': typeof AppAdminApiKeysLazyRoute
  '/admin/audit': typeof AppAdminAuditLazyRoute
  '/admin/roles': typeof AppAdminRolesLazyRoute
  '/admin/users': typeof AppAdminUsersLazyRoute
  '/wg/endpoints': typeof AppWgEndpointsLazyRoute
  '/wg/forwards': typeof AppWgForwardsLazyRoute
  '/wg/socks': typeof AppWgSocksLazyRoute
  '/wg/stats': typeof AppWgStatsLazyRoute
  '/wg/interfaces/$interfaceId': typeof AppWgInterfacesInterfaceIdLazyRoute
  '/wg/nodes/$nodeId': typeof AppWgNodesNodeIdLazyRoute
  '/wg/peers/$peerId': typeof AppWgPeersPeerIdLazyRoute
  '/wg/peers': typeof AppWgPeersIndexRoute
  '/wg/nodes': typeof AppWgNodesIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/activity': typeof AppActivityLazyRoute
  '/_app/jobs': typeof AppJobsLazyRoute
  '/_app/profile': typeof AppProfileLazyRoute
  '/_app/security': typeof AppSecurityLazyRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/_auth/sign-in': typeof AuthSignInLazyRoute
  '/_auth/sign-up': typeof AuthSignUpLazyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/api-keys': typeof AppAdminApiKeysLazyRoute
  '/_app/admin/audit': typeof AppAdminAuditLazyRoute
  '/_app/admin/roles': typeof AppAdminRolesLazyRoute
  '/_app/admin/users': typeof AppAdminUsersLazyRoute
  '/_app/wg/endpoints': typeof AppWgEndpointsLazyRoute
  '/_app/wg/forwards': typeof AppWgForwardsLazyRoute
  '/_app/wg/socks': typeof AppWgSocksLazyRoute
  '/_app/wg/stats': typeof AppWgStatsLazyRoute
  '/_app/wg/interfaces/$interfaceId': typeof AppWgInterfacesInterfaceIdLazyRoute
  '/_app/wg/nodes/$nodeId': typeof AppWgNodesNodeIdLazyRoute
  '/_app/wg/peers/$peerId': typeof AppWgPeersPeerIdLazyRoute
  '/_app/wg/peers/': typeof AppWgPeersIndexRoute
  '/_app/wg/nodes/': typeof AppWgNodesIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/activity'
    | '/jobs'
    | '/profile'
    | '/security'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/users'
    | '/wg/endpoints'
    | '/wg/forwards'
    | '/wg/socks'
    | '/wg/stats'
    | '/wg/interfaces/$interfaceId'
    | '/wg/nodes/$nodeId'
    | '/wg/peers/$peerId'
    | '/wg/peers/'
    | '/wg/nodes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/activity'
    | '/jobs'
    | '/profile'
    | '/security'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/users'
    | '/wg/endpoints'
    | '/wg/forwards'
    | '/wg/socks'
    | '/wg/stats'
    | '/wg/interfaces/$interfaceId'
    | '/wg/nodes/$nodeId'
    | '/wg/peers/$peerId'
    | '/wg/peers'
    | '/wg/nodes'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/reset-password'
    | '/_app/activity'
    | '/_app/jobs'
    | '/_app/profile'
    | '/_app/security'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/admin/api-keys'
    | '/_app/admin/audit'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/wg/endpoints'
    | '/_app/wg/forwards'
    | '/_app/wg/socks'
    | '/_app/wg/stats'
    | '/_app/wg/interfaces/$interfaceId'
    | '/_app/wg/nodes/$nodeId'
    | '/_app/wg/peers/$peerId'
    | '/_app/wg/peers/'
    | '/_app/wg/nodes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/admin/api-keys': {
      id: '/_app/admin/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AppAdminApiKeysLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wg/endpoints': {
      id: '/_app/wg/endpoints'
      path: '/wg/endpoints'
      fullPath: '/wg/endpoints'
      preLoaderRoute: typeof AppWgEndpointsLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wg/forwards': {
      id: '/_app/wg/forwards'
      path: '/wg/forwards'
      fullPath: '/wg/forwards'
      preLoaderRoute: typeof AppWgForwardsLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wg/socks': {
      id: '/_app/wg/socks'
      path: '/wg/socks'
      fullPath: '/wg/socks'
      preLoaderRoute: typeof AppWgSocksLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wg/stats': {
      id: '/_app/wg/stats'
      path: '/wg/stats'
      fullPath: '/wg/stats'
      preLoaderRoute: typeof AppWgStatsLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wg/interfaces/$interfaceId': {
      id: '/_app/wg/interfaces/$interfaceId'
      path: '/wg/interfaces/$interfaceId'
      fullPath: '/wg/interfaces/$interfaceId'
      preLoaderRoute: typeof AppWgInterfacesInterfaceIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wg/nodes/': {
      id: '/_app/wg/nodes/'
      path: '/wg/nodes'
      fullPath: '/wg/nodes/'
      preLoaderRoute: typeof AppWgNodesIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wg/nodes/$nodeId': {
      id: '/_app/wg/nodes/$nodeId'
      path: '/wg/nodes/$nodeId'
      fullPath: '/wg/nodes/$nodeId'
      preLoaderRoute: typeof AppWgNodesNodeIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wg/peers/': {
      id: '/_app/wg/peers/'
      path: '/wg/peers'
      fullPath: '/wg/peers/'
      preLoaderRoute: typeof AppWgPeersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wg/peers/$peerId': {
      id: '/_app/wg/peers/$peerId'
      path: '/wg/peers/$peerId'
      fullPath: '/wg/peers/$peerId'
      preLoaderRoute: typeof AppWgPeersPeerIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityLazyRoute: typeof AppActivityLazyRoute
  AppJobsLazyRoute: typeof AppJobsLazyRoute
  AppProfileLazyRoute: typeof AppProfileLazyRoute
  AppSecurityLazyRoute: typeof AppSecurityLazyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminApiKeysLazyRoute: typeof AppAdminApiKeysLazyRoute
  AppAdminAuditLazyRoute: typeof AppAdminAuditLazyRoute
  AppAdminRolesLazyRoute: typeof AppAdminRolesLazyRoute
  AppAdminUsersLazyRoute: typeof AppAdminUsersLazyRoute
  AppWgEndpointsLazyRoute: typeof AppWgEndpointsLazyRoute
  AppWgForwardsLazyRoute: typeof AppWgForwardsLazyRoute
  AppWgSocksLazyRoute: typeof AppWgSocksLazyRoute
  AppWgStatsLazyRoute: typeof AppWgStatsLazyRoute
  AppWgInterfacesInterfaceIdLazyRoute: typeof AppWgInterfacesInterfaceIdLazyRoute
  AppWgNodesNodeIdLazyRoute: typeof AppWgNodesNodeIdLazyRoute
  AppWgPeersPeerIdLazyRoute: typeof AppWgPeersPeerIdLazyRoute
  AppWgPeersIndexRoute: typeof AppWgPeersIndexRoute
  AppWgNodesIndexLazyRoute: typeof AppWgNodesIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityLazyRoute: AppActivityLazyRoute,
  AppJobsLazyRoute: AppJobsLazyRoute,
  AppProfileLazyRoute: AppProfileLazyRoute,
  AppSecurityLazyRoute: AppSecurityLazyRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminApiKeysLazyRoute: AppAdminApiKeysLazyRoute,
  AppAdminAuditLazyRoute: AppAdminAuditLazyRoute,
  AppAdminRolesLazyRoute: AppAdminRolesLazyRoute,
  AppAdminUsersLazyRoute: AppAdminUsersLazyRoute,
  AppWgEndpointsLazyRoute: AppWgEndpointsLazyRoute,
  AppWgForwardsLazyRoute: AppWgForwardsLazyRoute,
  AppWgSocksLazyRoute: AppWgSocksLazyRoute,
  AppWgStatsLazyRoute: AppWgStatsLazyRoute,
  AppWgInterfacesInterfaceIdLazyRoute: AppWgInterfacesInterfaceIdLazyRoute,
  AppWgNodesNodeIdLazyRoute: AppWgNodesNodeIdLazyRoute,
  AppWgPeersPeerIdLazyRoute: AppWgPeersPeerIdLazyRoute,
  AppWgPeersIndexRoute: AppWgPeersIndexRoute,
  AppWgNodesIndexLazyRoute: AppWgNodesIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthForgotPasswordLazyRoute: typeof AuthForgotPasswordLazyRoute
  AuthSignInLazyRoute: typeof AuthSignInLazyRoute
  AuthSignUpLazyRoute: typeof AuthSignUpLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthForgotPasswordLazyRoute: AuthForgotPasswordLazyRoute,
  AuthSignInLazyRoute: AuthSignInLazyRoute,
  AuthSignUpLazyRoute: AuthSignUpLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
